#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string YES = "Yes";

const std::string NO = "No";

void solve(std::string w) {
    bool answer = true;

    std::vector<int> chars(26, 0);

    for (unsigned int i = 0; i < w.size(); i++) {
        int charcode = w[i] - 'a';
        chars[charcode] += 1;
    }

    for (int i = 0; i < 26; i++) {
        if (chars[i] % 2 != 0) {
            answer = false;
        }
    }

    std::cout << (answer ? YES : NO) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    std::string w = input();
    solve(w);
    return 0;
}
