#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, std::vector<std::string> s, long long M, std::vector<std::string> t) {
    long long answer = 0;

    for (auto value: s) {
        int current = std::count(s.begin(), s.end(), value) - std::count(t.begin(), t.end(), value);
        if (answer < current) {
            answer = current;
        }
    }

    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    std::vector<std::string> s(N);
    for(int i = 0 ; i < N ; i++){
        s[i] = static_cast<std::string>(input());
    }
    long long M;
    M = input();
    std::vector<std::string> t(M);
    for(int i = 0 ; i < M ; i++){
        t[i] = static_cast<std::string>(input());
    }
    solve(N, std::move(s), M, std::move(t));
    return 0;
}
