#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, long long D, long long X, std::vector<long long> A) {
    long long answer = X;
    for (int i = 0; i < N; i++) {
        for (int j = 1; j <= D; j += A[i]) {
            answer++;
        }
    }
    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    long long D;
    D = input();
    long long X;
    X = input();
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        A[i] = input();
    }
    solve(N, D, X, std::move(A));
    return 0;
}
