#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string ERROR = "error";

void solve(int a, int b) {

    long long answer = a + b;
    if (answer >= 10) {
        std::cout << ERROR << std::endl;
    } else {
        std::cout << answer << std::endl;
    }
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    int a = input();
    int b = input();
    solve(a, b);
    return 0;
}
