#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(double x) {
    std::string answer = "";
    int y = (x - std::floor(x)) * 10;
    if (y <= 2) {
        answer = "-";
    } else if (y <= 6) {
        answer = "";
    } else {
        answer = "+";
    }
    std::cout << std::floor(x) << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    double x = input();
    solve(x);
    return 0;
}
