#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long n) {
    long long temp = n;
    long long answer = 0;
    long long factor = 1;

    while (0 < temp) {
        int digit = temp % 10;
        if (digit == 9) {
            digit = 1;
        } else if (digit == 1) {
            digit = 9;
        }
        answer += digit * factor;
        temp /= 10;
        factor *= 10;
    }

    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long n;
    n = input();
    solve(n);
    return 0;
}
