#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, long long M, long long X, std::vector<long long> A) {
    int lt = 0;
    int gt = 0;

    for (auto a: A) {
        if (a < X) {
            lt++;
        } else {
            gt++;
        }
    }

    long long answer = std::min(lt, gt);
    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    long long M;
    M = input();
    long long X;
    X = input();
    std::vector<long long> A(M);
    for(int i = 0 ; i < M ; i++){
        A[i] = input();
    }
    solve(N, M, X, std::move(A));
    return 0;
}
