#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(std::vector<long long> A) {
    std::sort(A.begin(), A.end(), std::greater<long long>());


    long long answer = (A[0] - A[1]) + (A[1] - A[2]);
    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    std::vector<long long> A(3);
    for(int i = 0 ; i < 3 ; i++){
        A[i] = input();
    }
    solve(std::move(A));
    return 0;
}
