#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(std::string S) {
    int length = S.length();

    int i = 0;
    while (i < length) {
        if (S[i] == 'd') {
            if (S.substr(i, 5) == "dream") {
                if (S.substr(i, 7) == "dreamer") {
                    if (S[i + 7] != 'a') {
                        i += 7;
                    } else {
                        i += 5;
                    }
                } else {
                    i += 5;
                }
            } else {
                std::cout << NO << std::endl;
                return;
            }
        } else if (S[i] == 'e') {
            if (S.substr(i, 5) == "erase") {
                if (S[i + 5] == 'r') {
                    i += 6;
                } else {
                    i += 5;
                }
            } else {
                std::cout << NO << std::endl;
                return;
            }
        } else {
            std::cout << NO << std::endl;
            return;
        }
    }

    std::cout << YES << std::endl;
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
