#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string YES = "Yes";

const std::string NO = "No";

void solve(long long a, long long b, long long c) {
    std::vector<long long> bags(3, 0);
    bags[0] = a;
    bags[1] = b;
    bags[2] = c;

    std::sort(bags.begin(), bags.end());

    bool answer = bags[0] + bags[1] == bags[2];

    std::cout << (answer ? YES : NO) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long a;
    a = input();
    long long b;
    b = input();
    long long c;
    c = input();
    solve(a, b, c);
    return 0;
}
