#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long x) {
    long long divided = x / 11;
    long long left = x - (divided * 11);
    long long answer = divided * 2;
    if (left == 0) {
        // do nothing
    } else if (left <= 6) {
        answer += 1;
    } else {
        answer += 2;
    }

    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long x;
    x = input();
    solve(x);
    return 0;
}
