#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(std::string X, std::string Y) {

    if (X[0] == Y[0]) {
        std::cout << "=" << std::endl;
    } else if (X[0] > Y[0]) {
        std::cout << ">" << std::endl;
    } else {
        std::cout << "<" << std::endl;
    }

}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    std::string X = input();
    std::string Y = input();
    solve(X, Y);
    return 0;
}
