#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string YES = "Yes";

const std::string NO = "No";

void solve(long long a, long long b) {
    long long target = a * (std::pow(10, std::ceil(std::log10(b+1)))) + b;
    bool answer = false;

    for (int i = 1; i*i <= target; i++) {
        if (i*i == target) {
            answer = true;
        }
    }

    std::cout << (answer ? YES : NO) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long a;
    a = input();
    long long b;
    b = input();
    solve(a, b);
    return 0;
}
