#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, std::vector<long long> A, long long X) {
    long long sum = std::accumulate(A.begin(), A.end(), 0LL);

    long long factor = X / sum;
    long long answer = factor * N;

    long long value = factor * sum;
    if (value <= X) {
        for (int i = 0; value <= X && i < N; i++) {
            value += A[i];
            answer += 1;
        }
    }

    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        A[i] = input();
    }
    long long X;
    X = input();
    solve(N, std::move(A), X);
    return 0;
}
