#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, std::vector<long long> A) {
    std::vector<long long> index(A);
    std::iota(index.begin(), index.end(), 0);

    std::sort(index.begin(), index.end(), [&A](long long a, long long b) -> bool {
        return A[a] > A[b];
    });

    std::cout << index[1] + 1 << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        A[i] = input();
    }
    solve(N, std::move(A));
    return 0;
}
