#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, long long A, long long B) {
    long long answer = 0;
    for (long long i = 1; i <= N; i++) {
        int sum = (i / 10000 % 10) + (i / 1000 % 10) + (i / 100 % 10) + (i / 10 % 10) + (i % 10);
        if (A <= sum && sum <= B) {
            answer += i;
        }
    }

    std::cout << answer << "\n";
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    long long N = input();
    long long A = input();
    long long B = input();
    solve(N, A, B);
    return 0;
}
