#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string YES = "YES";

const std::string NO = "NO";

void solve(std::string s1, std::string s2) {
    bool answer = (s1[0] == s2[2] && s1[1] == s2[1] && s1[2] == s2[0]);
    std::cout << (answer ? YES : NO) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    // Failed to predict input format
    std::string s1 = input();
    std::string s2 = input();
    solve(std::move(s1), std::move(s2));
    return 0;
}
