#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N, long long K, std::vector<long long> x) {
    long long answer = 0;
    for (long long const& pos : x) {
        answer += std::min(pos, std::abs(pos - K));
    }

    std::cout << (answer * 2LL) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    long long K;
    K = input();
    std::vector<long long> x(N);
    for(int i = 0 ; i < N ; i++){
        x[i] = input();
    }
    solve(N, K, std::move(x));
    return 0;
}
