#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

const std::string YES = "Yes";

const std::string NO = "No";

void solve(long long x, long long y) {
    bool answer = false;

    if (x == 2) {
        answer = (y == 2);
    } else if (x == 4 || x == 6 || x == 9 || x == 11) {
        answer = (y == 4 || y == 6 || y == 9 || y == 11);
    } else if (x == 1 || x == 3 || x == 5 || x == 7 || x == 8 || x == 10 ||
               x == 12) {
        answer = (y == 1 || y == 3 || y == 5 || y == 7 || y == 8 || y == 10 ||
                  y == 12);
    }
    std::cout << (answer ? YES : NO) << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long x;
    x = input();
    long long y;
    y = input();
    solve(x, y);
    return 0;
}
