#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long N) {
    // 105, 135, 165, 189, 195

    long long answer = 0;
    if (105 <= N) {
        answer++;
    }
    if (135 <= N) {
        answer++;
    }
    if (165 <= N) {
        answer++;
    }
    if (189 <= N) {
        answer++;
    }
    if (195 <= N) {
        answer++;
    }
    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long N;
    N = input();
    solve(N);
    return 0;
}
