#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve1() {
    std::cout << "Hello World" << std::endl;
}

void solve2(int a, int b) {
    long long answer = a + b;
    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    // Failed to predict input format
    int mode = input();
    if (mode == 1) {
        solve1();
    } else {
        int a = input();
        int b = input();
        solve2(a, b);
    }
    return 0;
}
