#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

struct input {
    template <class T> operator T() {
        T t;
        std::cin >> t;
        return t;
    }
};

void solve(long long X, long long A, long long B) {
    std::string answer;
    if (B <= A) {
        answer = "delicious";
    } else if (B <= A + X) {
        answer = "safe";
    } else {
        answer = "dangerous";
    }

    std::cout << answer << std::endl;
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools
int main() {
    long long X;
    X = input();
    long long A;
    A = input();
    long long B;
    B = input();
    solve(X, A, B);
    return 0;
}
